#!/bin/bash

# Make this file executable "chmod 700 script" and run "./script" to download the 
# necessary files. Executable "git" must be installed first. "sudo apt install git"

wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/io_ports/switch_bounce/switch_example.c
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/io_ports/switch_bounce/Makefile
git clone https://github.com/rltraylor/hd44780_driver.git
