#!/bin/bash
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/adc_new/adc_skel.c
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/adc_new/Makefile   
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/adc_new/hd44780.c 
wget http://www.ece.orst.edu/~traylor/ece473/inclass_exercises/adc_new/hd44780.h 
